### ISSUE TITLE
pip3 install update

### ISSUE THREAD

**Issue by jyami-kim** [junho85/garden4#28]
wiki 잘 읽었습니다 :)
따라서 해보고있는데, 
```shell
source env/bin/activate
```
이부분을
```shell
source venv/bin/activate
```
로 수정해야할 것 같습니다! 그리고

python 설치중에,
![image](https://user-images.githubusercontent.com/26458200/72627186-6244bd00-398f-11ea-8314-f9b98ec6f84e.png)
이런 에러가 났었는데 requirement.txt 도 같이 수정하면 좋을 것 같습니다 :)

사실 저는 파이썬, 장고를 처음 써봤어서 헤멨는데ㅠㅠㅠ
그럼에도 불구하고 문서를 너무 친절하게 써주셔서 조금씩 해볼 수 있었습니다 감사합니다

**Comment by junho85** [comment]
@mjung1798 
env -> venv 수정 했습니다 :)
requirements.txt 도 수정했습니다. markdown 이 메이저 버전업 하면서 뭔가 안맞게 되었나 보네요.
